Passku.WebCoreApp/Controllers/PasswordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using Passku.Business.Concrete.MongoDb;
using Passku.Cryptology;
using Passku.Models.Concrete;
using Passku.WebCoreApp.Helpers.Auth;

namespace Passku.WebCoreApp.Controllers
{
    public class PasswordController : Controller
    {

        UserManager userManager { get; set; }
        StoredPasswordManager storedPasswordManager { get; set; }

        public PasswordController(UserManager userManager, StoredPasswordManager storedPasswordManager)
        {
            this.userManager = userManager;
            this.storedPasswordManager = storedPasswordManager;
        }



        /* Create New Password */
        [AuthFilter]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(StoredPassword storedPassword)
        {
            var userId = new ObjectId(HttpContext.Session.GetString("SessionUserId").ToString());
            if (storedPassword.Password.Length >= 3 && storedPassword.Title.Length >= 3)
            {
                // Password Encrypt
                PasswordCryptology passwordCryptology = new PasswordCryptology();
                storedPassword.Password = passwordCryptology.Encrypt(storedPassword.Password);

                storedPassword.CreatedDate = DateTime.Now.ToShortDateString();
                storedPassword.UserId = userId;
                storedPasswordManager.Add(storedPassword);
                TempData["MsgPasswordAddSuccessful"] = "Your password has been successfully saved in the system.";
                return RedirectToAction("Passwords", "User");
            }
            return View(storedPassword);
        }



        /* Read Password By Id */
        [AuthFilter]
        public IActionResult Detail(string id)
        {
            var userId = new ObjectId(HttpContext.Session.GetString("SessionUserId").ToString());
            var password = storedPasswordManager.GetById(id);
            if (password == null)
            {
                return RedirectToAction("Error", "User");
            }
            if (password.UserId != userId)
            {
                return RedirectToAction("Error", "User");
            }

            // Password Decrypt
            PasswordCryptology passwordCryptology = new PasswordCryptology();
            password.Password = passwordCryptology.Decrypt(password.Password);

            return View(password);
        }



        /* Edit Password By Id */
        [AuthFilter]
        public IActionResult Edit(string id)
        {
            var userId = new ObjectId(HttpContext.Session.GetString("SessionUserId").ToString());
            var password = storedPasswordManager.GetById(id);
            if (password == null)
            {
                return RedirectToAction("Error", "User");
            }
            if (password.UserId != userId)
            {
                return RedirectToAction("Error", "User");
            }

            // Password Decrypt
            PasswordCryptology passwordCryptology = new PasswordCryptology();
            password.Password = passwordCryptology.Decrypt(password.Password);

            return View(password);
        }
        [HttpPost]
        public IActionResult Edit(string id, StoredPassword storedPassword)
        {
            var item = storedPasswordManager.GetById(id);
            if (storedPassword.Password.Length >= 3 && storedPassword.Title.Length >= 3)
            {
                // Password Encrypt
                PasswordCryptology passwordCryptology = new PasswordCryptology();

                item.Title = storedPassword.Title;
                item.Password = passwordCryptology.Encrypt(storedPassword.Password);
                item.Content = storedPassword.Content;
                item.Url = storedPassword.Url;
                storedPasswordManager.Update(id, item);
                TempData["MsgPasswordEditSuccessful"] = "Your password has been successfully edited in the system.";
                return RedirectToAction("Passwords", "User");
            }
            return View(storedPassword);
        }



        /* Delete Password By Id */
        [AuthFilter]
        public IActionResult Delete(string id)
        {
            var userId = new ObjectId(HttpContext.Session.GetString("SessionUserId").ToString());
            var password = storedPasswordManager.GetById(id);
            if (password == null)
            {
                return RedirectToAction("Error", "User");
            }
            if (password.UserId != userId)
            {
                return RedirectToAction("Error", "User");
            }

            // Password Decrypt
            PasswordCryptology passwordCryptology = new PasswordCryptology();
            password.Password = passwordCryptology.Decrypt(password.Password);

            return View(password);
        }
        [HttpPost]
        public IActionResult Delete(string id, IFormCollection collection)
        {
            var userId = new ObjectId(HttpContext.Session.GetString("SessionUserId").ToString());
            var password = storedPasswordManager.GetById(id);
            if (password == null)
            {
                return RedirectToAction("Error", "User");
            }
            if (password.UserId != userId)
            {
                return RedirectToAction("Error", "User");
            }
            storedPasswordManager.Delete(id);
            TempData["MsgPasswordDeleteSuccessful"] = "Your password has been successfully deleted in the system.";
            return RedirectToAction("Passwords","User");
        }


    }
}

Passku.WebCoreApp/Views/Password/Add.cshtml
@model Passku.Models.Concrete.StoredPassword
@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <strong class="card-title">Add New Password</strong>
            </div>
            <div class="card-body">
                <div id="pay-invoice">
                    <div class="card-body">
                        <form asp-controller="Password" asp-action="Add" method="post" enctype="multipart/form-data">

                            <div class="form-group">
                                <label class="control-label mb-1">Title</label>
                                <input asp-for="Title" type="text" class="form-control" placeholder="Enter Password Title..." required/>
                            </div>

                            <div class="form-group">
                                <label class="control-label mb-1">Password</label>
                                <input asp-for="Password" type="text" class="form-control" placeholder="Enter Your Password..." required>
                            </div>

                            <div class="form-group">
                                <label class="control-label mb-1">Content</label>
                                <textarea asp-for="Content" class="form-control" placeholder="Enter Password Description..." rows="3"></textarea>
                            </div>

                            <div class="form-group">
                                <label class="control-label mb-1">Url</label>
                                <input asp-for="Url" type="text" class="form-control" placeholder="Enter Password Title..." />
                            </div>

                            <div>
                                <button type="submit" class="btn btn-lg btn-info btn-block">
                                    <i class="fa fa-plus-circle fa-lg"></i>&nbsp;
                                    <span id="payment-button-amount">Add New Password</span>
                                </button>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>

Passku.WebCoreApp/Views/Password/Delete.cshtml
@model Passku.Models.Concrete.StoredPassword
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <strong class="card-title">Delete Password</strong>
            </div>
            <div class="card-body">
                <div id="pay-invoice">
                    <div class="card-body">
                        <form asp-controller="Password" asp-action="Delete" method="post" enctype="multipart/form-data">

                            <div class="form-group">
                                <label class="control-label mb-1">Title</label>
                                <input asp-for="Title" type="text" class="form-control" value="@Model.Title" readonly>
                            </div>

                            <div class="form-group">
                                <label class="control-label mb-1">Password</label>
                                <input asp-for="Password" type="text" class="form-control" value="@Model.Password" readonly>
                            </div>

                            <div class="form-group">
                                <label class="control-label mb-1">Content</label>
                                <textarea asp-for="Content" class="form-control" rows="3" readonly>@Model.Content</textarea>
                            </div>

                            <div class="form-group">
                                <label class="control-label mb-1">Url</label>
                                <input asp-for="Url" type="text" class="form-control" value="@Model.Url" readonly />
                            </div>

                            <div class="form-group">
                                <label class="control-label mb-1">Created Date</label>
                                <input asp-for="CreatedDate" type="text" class="form-control" value="@Model.CreatedDate" readonly />
                            </div>

                            <div>
                                <button type="submit" class="btn btn-lg btn-danger btn-block">
                                    <i class="fa fa-trash fa-lg"></i>&nbsp;
                                    <span id="payment-button-amount">Delete Password</span>
                                </button>
                            </div>

                        </form>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>

Passku.WebCoreApp/Views/Password/Detail.cshtml
@model Passku.Models.Concrete.StoredPassword
@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <strong class="card-title">Update Password</strong>
            </div>
            <div class="card-body">
                <div id="pay-invoice">
                    <div class="card-body">
                        <form asp-controller="" asp-action="" method="post" enctype="multipart/form-data">

                            <div class="form-group">
                                <label class="control-label mb-1">Title</label>
                                <input asp-for="Title" type="text" class="form-control" value="@Model.Title" readonly>
                            </div>

                            <div class="form-group">
                                <label class="control-label mb-1">Password</label>
                                <input asp-for="Password" type="text" class="form-control" value="@Model.Password" readonly>
                            </div>

                            <div class="form-group">
                                <label class="control-label mb-1">Content</label>
                                <textarea asp-for="Content" class="form-control" rows="3" readonly>@Model.Content</textarea>
                            </div>

                            <div class="form-group">
                                <label class="control-label mb-1">Url</label>
                                <input asp-for="Url" type="text" class="form-control" value="@Model.Url" readonly />
                            </div>

                            <div class="form-group">
                                <label class="control-label mb-1">Created Date</label>
                                <input asp-for="CreatedDate" type="text" class="form-control" value="@Model.CreatedDate" readonly />
                            </div>

                            <div class="row">
                                <div class="col-md-4">
                                    <center><a href="/User/Passwords/" class="btn btn-success" style="margin-bottom:10px;"><i class="fa fa-angle-double-left"></i> Back Page</a></center>
                                </div>
                                <div class="col-md-4">
                                    <center><a href="/Password/Edit/@Model.Id" class="btn btn-warning" style="margin-bottom:10px;"><i class="fa fa-pencil"></i> Edit Password</a></center>
                                </div>
                                <div class="col-md-4">
                                    <center><a href="/Password/Delete/@Model.Id" class="btn btn-danger" style="margin-bottom:10px;"><i class="fa fa-trash"></i> Delete Password</a></center>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>

Passku.WebCoreApp/Views/Password/Edit.cshtml
@model Passku.Models.Concrete.StoredPassword
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <strong class="card-title">Update Password</strong>
            </div>
            <div class="card-body">
                <div id="pay-invoice">
                    <div class="card-body">
                        <form asp-controller="Password" asp-action="Edit" method="post" enctype="multipart/form-data">

                            <div class="form-group">
                                <label class="control-label mb-1">Title</label>
                                <input asp-for="Title" type="text" class="form-control" value="@Model.Title" required>
                            </div>

                            <div class="form-group">
                                <label class="control-label mb-1">Password</label>
                                <input asp-for="Password" type="text" class="form-control" value="@Model.Password" required>
                            </div>

                            <div class="form-group">
                                <label class="control-label mb-1">Content</label>
                                <textarea asp-for="Content" class="form-control" rows="3">@Model.Content</textarea>
                            </div>

                            <div class="form-group">
                                <label class="control-label mb-1">Url</label>
                                <input asp-for="Url" type="text" class="form-control" value="@Model.Url" />
                            </div>

                            <div>
                                <button type="submit" class="btn btn-lg btn-success btn-block">
                                    <i class="fa fa-plus-pencil fa-lg"></i>&nbsp;
                                    <span id="payment-button-amount">Edit Password</span>
                                </button>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>